### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by SOOOIN** [SOOOIN/todoApp_repository-#2]
# Getting Started with Create React App   
### 직접 Github 리포지토리를 만들고, 아래 항목을 제작합니다.   <br>
1.  [x] 과제 제출 여부를 확인할 수 있게, public으로 제작합니다.   
-------------------
### 아래 파일을 포함합니다.
1. [x] README.md
2. [x] .gitignore
3. [x] LICENSE
-------------------
### Github Project 칸반
1. [x] Todo App을 직접 만든다고 생각하고 이슈, 마일스톤을 스스로 정해봅니다.
2. [x] Github Project 칸반을 만들고, 이슈와 마일스톤을 연결하고 칸반 뷰로 변경합니다.
-------------------
### Coz’ Git flow
1. [x] 직접 제작한 Github 리포지토리에 main, dev 브랜치를 만듭니다.
2. [x] dev 브랜치에서 main 브랜치로 Pull Request를 최소 1회 시도합니다.
-------------------
### Create React App을 활용해 프론트엔드 개발에 유용한 프레임워크를 설치해봅니다.
1. [x] Redux
2. [x] Styled-Component
3. [x] ESLint, Prettier
